baseURL: "//seblaise.dev/"
title: Blaise Sebagabo - Developer, Designer, Founder
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-2NK5Y7DW5J

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: BlaiseSebagabo
  description: "I'm Blaise, a software developer at TELUS with extensive experience across a wide spectrum of technologies including .NET, JavaScript, and Rails. My career journey has led me to work with esteemed companies such as AltaML and Alberta Health Services, where I contributed significantly to high-impact projects like the Covid Testing and Immunization Booking applications. My ability to navigate a diverse array of programming languages, cloud infrastructures, and software tools, paired with my effective teamwork and leadership skills, enables me to confidently address both front-end and backend challenges. Beyond the technical, I'm proud to hold certifications such as the GCP - Cloud Digital Leader and Certified SAFe® 5 Practitioner. Whether working on a professional project or enhancing my personal development website, my passion for coding and technology is always evident."
  keywords: [Blog, Portfolio, PaperMod]
  author: Blaise Sebagabo
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Blaise Sebagabo"
    icon: images/coding.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: ExampleSite
    subtitle: "This is subtitle"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: I'm Blaise, currently furthering innovation at TELUS as a Full-stack Software Developer. I bring a wealth of experience in .NET, JavaScript, Rails, and many other technologies, accumulated through my time with companies such as AltaML and Alberta Health Services. There, I made substantial contributions to high-stakes projects, including the development of Covid Testing and Immunization Booking applications. My skill set spans various programming languages, cloud infrastructures, and software tools, complemented by my teamwork, leadership, and excellent communication skills. This diverse competence allows me to effectively tackle any challenge - be it front-end or backend. Proudly, I hold certifications like the GCP - Cloud Digital Leader and Certified SAFe® 5 Practitioner, reflecting my continuous pursuit of professional growth. Whether spearheading a project or refining my personal development website, my passion for coding and technology shines through in every endeavor.
  socialIcons:
    - name: linkedIn
      url: "https://linkedIn.com/in/blaise94"
    - name: stackoverflow
      url: "https://stackoverflow.com/users/12550133"
    - name: github
      url: "https://github.com/blaiseAi"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/blaiseAI/seblaise-2.0/tree/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    # - identifier: categories
    #   name: categories
    #   url: /categories/
    #   weight: 10
    # - identifier: tags
    #   name: tags
    #   url: /tags/
    #   weight: 20
    - identifier: about
      name: About
      url: /about/
      weight: 1
    - identifier: blog
      name: Blog
      url: /blogs/
      weight: 2
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 3
    - identifier: snippets
      name: Snippets
      url: /snippets/
      weight: 3
    - identifier: store
      name: dev store
      url: http://seblaise.creator-spring.com
      weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
